config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
  resources :users, except: [:new]

  get 'signup', to: 'users#new'

  post 'users', to: 'users#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: :true, length: {minimum:3, maximum:40}
  validates :description, presence: :true, length: {minimum:10, maximum:300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  before_save { self.username = username.capitalize }
  has_many :articles

  validates :username, :email, presence: true, uniqueness: { case_sensitive: false }
  validates :username, length: {minimum: 3, maximum: 25}
  validates :email, length: {maximum: 105}, format: { with: URI::MailTo::EMAIL_REGEXP }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = User.first

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to Open Blog, #{@user.username}! You have successfully signed up!"
      redirect_to articles_path
    else
      render "new"
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params) 
      flash[:notice] = "Your information successfully updated!"
      redirect_to @user
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email = user.email
    hash = Digest::MD5.hexdigest(email)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"

    image_tag(gravatar_url, alt:user.username, class:"rounded-circle shadow-lg mx-auto d-block")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="articles">
  <% @articles.reverse.each do |article| %>
    <div class="article-block my-4 shadow col-8">
      <div class="card text-center">
        <div class="card-header">
          <% if article.user %>
            <p class="fs-5 mt-3 fst-italic">by <%= link_to article.user.username, user_path(article.user), class:"mx-3" %></p>
          <% end %>
        </div>

        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class:"text-success" %></h5>
          <div class="card-text"><%= simple_format(truncate(article.description, length: 50)) %></div>
          <div class="container">
            <%= link_to "View", article_path(article.id), class:"article-actions btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(article.id), class:"article-actions btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article.id), method: :delete, data: { confirm: 'Are you sure?' }, class:"article-actions btn btn-outline-danger" %>
          </div>
        </div>
        <div class="card-footer text-muted">
          <p class="fs-6 mt-3">Created <%= time_ago_in_words(article.created_at) %> ago  <strong>|</strong>  Edited <%= time_ago_in_words(article.updated_at) %> ago</p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<%= form_with(model: @article, local: true) do |form| %>
  <div class="article-form card shadow-lg col-8">
    <div class="input-group mb-3">
      <%= form.label :title, class: "input-group-text fs-4 text-light", id: "title-field" do %>
        Title:
      <% end %>
      <%= form.text_field :title, class: "form-control shadow-lg rounded", id: "basic-url", aria: { describedby: "title-field" }, placeholder:"Title of article" %>
    </div>

    <div class="input-group mb-4">
      <%= form.label :description, class: "input-group-text fs-4 text-light" do %>
        Description:
      <% end %>
      <%= form.text_area :description, class: "form-control shadow-lg rounded", rows: 10, placeholder:"Description" %>
    </div>

    <p class="form-button">
      <%= form.submit "Save article!", class: "mt-4 btn btn-lg btn-outline-light col-4 shadow-lg" %>
    </p>
  </div>
<% end %>

<div class="my-4">
  <%= link_to '[ Cancel and return to articles listing ]', articles_path, class:"mb-4 cancel-link text-info d-flex justify-content-center" %>
</div>
<br class="mb-4">
<br>

app/views/articles/edit.html.erb
<h1 class="text-center my-4">Editing Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<!--<p id="notice"><%= notice %></p>
-->
<h1 class="text-center my-4">Listing all articles</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render "article" %>

<br>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>
<br>
.
<br>
.

app/views/articles/new.html.erb
<h1 class="text-center my-4">Create new article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h2 class="text-center my-4"><%= @article.title %></h2>

<div class="flex-n-center">
  <div class="article-block my-4 shadow col-8">
    <div class="card text-center">
      <div class="card-header">
        <p class="fs-5 mt-3 fst-italic">by <%= @article.user.username.capitalize if @article.user %></p>
        <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
      </div>

      <div class="card-body">
        <div class="card-text text-start mx-4"><%= simple_format(@article.description) %></div>
        <div class="container">
          <%= link_to "Edit", edit_article_path(@article.id), class:"article-actions btn btn-outline-info" %>
          <%= link_to "Delete", article_path(@article.id), method: :delete, data: { confirm: 'Are you sure?' }, class:"article-actions btn btn-outline-danger" %>
        </div>
      </div>
      <div class="card-footer text-muted">
        <p class="fs-6 mt-3">Created <%= time_ago_in_words(@article.created_at) %> ago  
        <strong>|</strong>  Edited <%= time_ago_in_words(@article.updated_at) %> ago</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<nav class="navbar pt-4 navbar-expand-lg footer fixed-bottom">

  <div class="text-center">
    <p>Copyright &copy; <%= link_to "Leon T", "https://leontraykov.github.io/cv/", class:"text-white text-decoration-none", target:"_blank" %></p>
  </div>
</nav>

app/views/layouts/_hero.html.erb
<div class="container hero my-4 text-center" id="hero">
  <h1 class="my-4">Open Blog</h1>
  <p class="lead">text Hero text Hero text Hero text </p>
  <hr class="my-4">
  <p class="hero-text">Hero text Hero text Hero text Hero text Hero text Hero text Hero text Hero text </p>
  <%= link_to "Sign up!", signup_path, class:"btn btn-success btn-lg" %>
</div>

app/views/layouts/_messages.html.erb
<div class="flex-n-center my-3">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success col-8 alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-black">
  <div class="container-fluid">
    <%= link_to "Open Blog", root_path, class:"navbar-brand", id:"logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><%= link_to 'Bloggers', users_path, class:"nav-link" %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'Articles listing', articles_path, class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Create new article', new_article_path, class:"dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Open Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "layouts/navigation" %>

    <div id="page-content">
      <%= render "layouts/messages" %>

      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>

<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>
<h1>This is ABOUT PAGE</h1>

app/views/pages/home.html.erb
  <%= render "layouts/hero" %>

  <%= link_to 'Articles listing', articles_path %> |
  <%= link_to 'About page', about_path %>

app/views/shared/_errors.html.erb
<div class="errors-block">
  <% if obj.errors.any? %>
    <div class="alert alert-danger col-8 alert-dismissible fade show" role="alert">
      <h4 class="alert-heading"><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class.name.downcase %> from being saved:</h4>
      <hr>
      <ul>
        <% obj.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>

<%= form_with(model: @user, local: true) do |form| %>
  <div class="article-form card shadow-lg col-8">
    <div class="input-group">
      <%= form.label :username, class: "input-group-text fs-4 text-light", id: "title-field" do %>
        Name:
      <% end %>
      <%= form.text_field :username, class: "form-control shadow-lg rounded", id: "basic-url", aria: { describedby: "title-field" }, placeholder:"Enter a username" %>
    </div>

    <div class="input-group mt-4">
      <%= form.label :email, class: "input-group-text fs-4 text-light" do %>
        Email:
      <% end %>
      <%= form.email_field :email, class: "form-control shadow-lg rounded", placeholder:"Enter your email address" %>
    </div>

    <div class="input-group my-4">
      <%= form.label :password, class: "input-group-text fs-4 text-light" do %>
        Password:
      <% end %>
      <%= form.password_field :password, class: "form-control shadow-lg rounded", placeholder:"Choose a password" %>
    </div>

    <p class="form-button">
      <%= form.submit(@user.new_record? ? "Sign up!" : "Update account", class: "mt-4 btn btn-lg btn-outline-light col-4 shadow-lg") %>
    </p>
  </div>
<% end %>

<div class="my-4">
  <%= link_to '[ Cancel and return to articles listing ]', articles_path, class:"mb-4 cancel-link text-info d-flex justify-content-center" %>
</div>
<br class="mb-4">
<br>

app/views/users/edit.html.erb
<h1 class="text-center my-4">Editing users information</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center my-4">Open Bloggers</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<div class="articles">
  <% @users.reverse.each do |user| %>
    <div class="article-block my-4 shadow col-8">
      <div class="card text-center">
        <div class="card-header">
          <p class="fs-3 mt-3 fst-italic"><%= link_to user.username.capitalize, user %></p>
        </div>
        <div class="card-body">
          <div class="card-title">
            <%= link_to gravatar_for(user, size: 150), user %>
          </div>

          <h5 class="card-text mx-4 my-4"><%= pluralize(user.articles.count, "article") %></h5>

          <div class="container">
            <%= link_to "View profile", user, class:"article-actions btn btn-outline-success" %>
            <%= link_to "Edit profile", edit_user_path(user), class:"article-actions btn btn-outline-info" %>
          </div>
        </div>
        <div class="card-footer text-muted">
          <h5 class="mx-4 my-4">Joined <%= time_ago_in_words(user.created_at) %></h5>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center my-4">Sign up for Open Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center my-4"><%= @user.username %>'s profile</h1>
<div class="user-info"> 
  <div class="my-4 shadow col-8">
    <div class="card text-center">
      <div class="card-header">
        <h5 class="card-title mx-4 my-4">Name: <%= @user.username %></h5>
      </div>

      <div class="card-body">

        <%= gravatar_for @user, size: 200 %>

        <div class="card-text"><h5 class="mx-4 my-4">Email: <%= @user.email %></h5></div>
        <h5 class="text-center my-4">Users id: #<%= @user.id %></h5>
        <div class="container">
          <%= link_to "Edit profile", edit_user_path(@user), class:"article-actions btn btn-outline-info" %>
        </div>
      </div>
      <div class="card-footer text-muted">
        <h5 class="mx-4 my-4">Member since:  <%= @user.created_at.strftime("%d.%m.%Y") %></h5>
      </div>
    </div>
  </div>
</div>
<br>
<h3 class="text-center my-4"><%= @user.username %>'s articles</h3>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render "articles/article" %>
<br>
<br>